version: '3'
services:
    app:
        container_name: docker-node-mongo
        restart: always
        build: .
        ports: 
            - '5000:5000'
        links:
            - mongo
            - redis
        environment: 
            - REDIS_URL=redis://redis
            - DB_URI=mongodb://mongo:27017/docker-node-mongo
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - '27017:27017'
    redis:
        container_name: redis
        image: redis
        ports: 
            - '6379:6379'
